workflows:
  ios-workflow:
    name: Flangapp PRO iOS without publication
    max_build_duration: 30
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_CONNECT_ISSUER_ID: d1e96a8b-4e81-425e-b0e7-7061ca9d4d4e
        APP_STORE_CONNECT_KEY_IDENTIFIER: MFBBPWQKX6
        APP_STORE_CONNECT_PRIVATE_KEY: |-
         -----BEGIN PRIVATE KEY-----
         MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgAaJziynTmyJsHvdX
         lNeV/PFt2Krv0teP9ti3oGKRWiigCgYIKoZIzj0DAQehRANCAARDtf8Ncpwju+Re
         MsOcXVb/vqYDXwT4RpMjkWROsAMC7YgmDC5hNP6czb3BsxqB8uj6inTAJMyRYxbK
         sN05cWoM
         -----END PRIVATE KEY-----

        CERTIFICATE_PRIVATE_KEY: |-
         -----BEGIN RSA PRIVATE KEY-----
         MIIEowIBAAKCAQEAy09JeqgOr1+gVtV4giKNem6ML1pcW2307bpDM+pOa5zdrv4H
         3UueTdIC5kfEl3DFF43ZWfmVuLhPHurRflc4YATw4hGeA5unvZtKsdEDXAfN7/q3
         6JjAo4cwf3aW97MxCq/wGEiN67NK+22xytppO7/eejZcOjkxxoGdy+yqcmqc3iRJ
         j/4Urixhe8VBzUHDCGgyZm5AWul5FgLtQ/2Wffenw/h432cOnODEzlQNX37UXlDj
         +0F7AyVVaLOXm0sWloqxrEZf8MnMtOtgYfDY6+dxBXTYKUp+Q8DIJEoRJp12ZjK6
         Lj4SRLAKoZLAwx1Cf7afsdZkr2nq+NpvOeI66wIDAQABAoIBAEHB8kUuyBkm98g+
         IU0N+e6IhOTn+AlGZjrhzMyk0xpxUS5BUa/cvmXzMCblPYux2L2Gjq9QT4HAcy7P
         ylRvx3cfAf5MrmwCU127NYyPyuNgTtZ4pDUh+uSpXCFN7QROu+T2BNUF2olKo0zx
         LNksjW7a3w1uOaRHTXckAzKq6HI6v8qlRQNOnVd1EisluCTqihen1g7uby94NvFn
         ntt9Y5r6wPdw38lSDtSbsXIHdbnSwzshQsdXB/24IA9XGaE25u5LXim0+FdEgldT
         o9aBogCPR4VyyQKKpnaMvCPO+qrWL+pnhxrS+6URJwaHyX+BTEEbc3A7JyIL5Ybv
         FV9sdvkCgYEA4F592aCpHkA86Z2DsNqo48H5Dl66Kdx7xT/KxyDmkUFJV5nQGXDK
         yAgxBkvlJg7Lfrt0W2/kJo74tLWL8+/PCHOdOo3OClJ0G6YIXy8C48n1TZh9Xo4Z
         gDEIr/6dgVGLM87OdzI363SXdulNeyLgJcJwt+mbY6h0/N6mhZL8fH8CgYEA5/jC
         Zmk+UngAuA5GvmkaLrRTRSLuesivr+2qmetvb7R7cdh4NlfYyuodOSHp3UN7cM+m
         WBuOa214V518h7tGbkfOxYwd/x5tV+4322IujWAOLjzumtazItiBNRDBRLn+/Ok1
         jZS6EmCvu+FY69Qc2E4eRglLkcs/L4z3APeDu5UCgYAkNtw1Tjs9yLyMMIJa/1AX
         Qu3CJgQCUbYghkVikqrkcxc1bnwqPwxb8QaIr6NS2zx5PiRvxcWbe6Qk9tCaFPDj
         ulV8Z/sDq39WHxxm0J20ypovZheGNYVkLYXrcjtV7iV7vTuR/acM+AqihNGeuGhZ
         b+LlrG0KTtxjHETgdnMOXQKBgQCLWxMWSQVqr7Lm35S6UROsmSIpN4oC80swKlxB
         6YFhnxBF3WCibPXNOQXjS69eAGtI40YwSiWt/e6829xzAhuWpsbeQIXIvLO9jlu6
         DOqgfeMm/e3t0St+tIgyo+Unb4Fy2HsWmhGKdtE70m4EBsJpY8ymEHF4nZxQ6aN9
         zjQyXQKBgGq2OJmUcPwB11HAu96tm1sawv6nWhoKyCgJvk5j/mwr5z2XN9RJp0Q0
         XYF8R9GDU/2s8OQU2S4gOL3bqJUApbMIyFL9RPS94aq5Lj2KSm8zhYgPZwl4FA3j
         rnmfzCC2448W/jfc2QmejmPTPloYx8N0hEePdndmlB959Wji7PmW
         -----END RSA PRIVATE KEY-----
         

        BUNDLE_ID: "online.allis.learning"
      flutter: 3.16.7
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create --log-api-calls --verbose
      - name: Use system default keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release --no-tree-shake-icons \
          --build-name=1.0.3 \
          --build-number=1 \
          --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      scripts:
        - name: HTTP notification
          script: |
            curl https://appbuilder.webcodeinfo.com/public/observe/notice?uid=b024ce30-d354-a2a5-be22-0accac315501