
class Config {

  /// Generated by Flangapp PRO 29-05-2024 17:51
  /// App UID: ca53d2ad-494e-f559-5954-09930166dc12
  /// Version: 1.0.0
  /// API server: https://appbuilder.webcodeinfo.com/

  /// *** Main settings *** ///
  static String apiUrl = "https://appbuilder.webcodeinfo.com/";
  static String appUid = "ca53d2ad-494e-f559-5954-09930166dc12";
  static String oneSignalPushId = "f0574392-2d11-47c9-a52f-db4eee22d64d";

  /// *** Splashscreen settings *** ///
  // Background color (any HEX color)
  static String splashBackgroundColor = "#000000";
  // Text color (any HEX color)
  static String splashTextColor = "#ffffff";
  // Is image background
  static bool splashIsBackgroundImage = false;
  // Background image name
  static String splashBackgroundImage = "splash_screen.png";
  // Tagline
  static String splashTagline = "";
  // Delay display (seconds)
  static int splashDelay = 3;
  // Logo image name
  static String splashLogoImage = "splash_logo.png";
  // Display logo
  static bool splashIsDisplayLogo = false;

  /// *** Offline localization settings *** ///
  static String offlineErrorMessage = "No internet connection";
  static String offlineImage = "dino.png";

  /// *** Subscribe need settings *** ///
  static String subscribeErrorTitle = "App not available";
  static String subscribeErrorMessage = "This app may have been removed or your administrator may need to renew your subscription";
}