
class Config {

  /// Generated by Flangapp PRO 16-05-2024 08:18
  /// App UID: d77dc16f-ab4b-b7e3-f1ce-5d87116c2c75
  /// Version: 1.0.2
  /// API server: https://appbuilder.webcodeinfo.com/

  /// *** Main settings *** ///
  static String apiUrl = "https://appbuilder.webcodeinfo.com/";
  static String appUid = "d77dc16f-ab4b-b7e3-f1ce-5d87116c2c75";
  static String oneSignalPushId = "";

  /// *** Splashscreen settings *** ///
  // Background color (any HEX color)
  static String splashBackgroundColor = "#000000";
  // Text color (any HEX color)
  static String splashTextColor = "#ffffff";
  // Is image background
  static bool splashIsBackgroundImage = true;
  // Background image name
  static String splashBackgroundImage = "splash_screen.png";
  // Tagline
  static String splashTagline = "";
  // Delay display (seconds)
  static int splashDelay = 3;
  // Logo image name
  static String splashLogoImage = "splash_logo.png";
  // Display logo
  static bool splashIsDisplayLogo = false;

  /// *** Offline localization settings *** ///
  static String offlineErrorMessage = "No internet connection";
  static String offlineImage = "dino.png";

  /// *** Subscribe need settings *** ///
  static String subscribeErrorTitle = "App not available";
  static String subscribeErrorMessage = "This app may have been removed or your administrator may need to renew your subscription";
}