
class Config {

  /// Generated by Flangapp PRO 17-04-2024 10:45
  /// App UID: cbf33aa8-80e6-7ccf-275a-162423b4682b
  /// Version: 1.0.1
  /// API server: https://appbuilder.webcodeinfo.com/

  /// *** Main settings *** ///
  static String apiUrl = "https://appbuilder.webcodeinfo.com/";
  static String appUid = "cbf33aa8-80e6-7ccf-275a-162423b4682b";
  static String oneSignalPushId = "b0aed9ff-fcb5-4914-b092-90b553059fef";

  /// *** Splashscreen settings *** ///
  // Background color (any HEX color)
  static String splashBackgroundColor = "#000000";
  // Text color (any HEX color)
  static String splashTextColor = "#ffffff";
  // Is image background
  static bool splashIsBackgroundImage = false;
  // Background image name
  static String splashBackgroundImage = "splash_screen.png";
  // Tagline
  static String splashTagline = "";
  // Delay display (seconds)
  static int splashDelay = 3;
  // Logo image name
  static String splashLogoImage = "splash_logo.png";
  // Display logo
  static bool splashIsDisplayLogo = false;

  /// *** Offline localization settings *** ///
  static String offlineErrorMessage = "No internet connection";
  static String offlineImage = "dino.png";

  /// *** Subscribe need settings *** ///
  static String subscribeErrorTitle = "App not available";
  static String subscribeErrorMessage = "This app may have been removed or your administrator may need to renew your subscription";
}